import './globals.css'

export const metadata = {
  title: 'Restaurant Booking App',
  description: 'Generated by Devzons',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  )
}
