import NavBar from './components/NavBar'
import AuthContext from './context/AuthContext'
import './globals.css'
import 'react-datepicker/dist/react-datepicker.css'

export const metadata = {
  title: 'OpenBooking',
  description: 'Generated by Devzons',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <head />
      <body>
        <main className='min-h-screen w-screen'>
          <AuthContext>
            <div className='w-full mx-10'>
              <NavBar />
              {children}
            </div>
          </AuthContext>
        </main>
      </body>
    </html>
  )
}
